import Head from 'next/head';
import CryptoSection from '../components/sections/CryptoSection/CryptoSection';
import HeroSection from '../components/sections/HeroSection';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeroSection />
      <CryptoSection />
    </div>
  );
}
